//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:192.168.123.6,1433;Initial Catalog=Tickets;Persist Security Info=" +
            "True;User ID=sa;Password=")]
        public string TicketsConnectionString {
            get {
                return ((string)(this["TicketsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:192.168.123.6,1433;Initial Catalog=Tickets;Persist Security Info=" +
            "True;User ID=sa")]
        public string TicketsConnectionString2 {
            get {
                return ((string)(this["TicketsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:192.168.123.6,1433;Initial Catalog=GAB_Irapuato;Persist Security " +
            "Info=True;User ID=sa;Password=Gabira2026$")]
        public string GAB_IrapuatoConnectionString {
            get {
                return ((string)(this["GAB_IrapuatoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:192.168.123.6,1433;Initial Catalog=GAB_Irapuato;Persist Security " +
            "Info=True;User ID=sa;Password=Gabira2026$")]
        public string GAB_IrapuatoConnectionString1 {
            get {
                return ((string)(this["GAB_IrapuatoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=GABSQL\\SQL2017;Initial Catalog=RESPALDO_GAB;Persist Security Info=Tru" +
            "e;User ID=saTest;Password=Gabira2026$;Encrypt=False;TrustServerCertificate=True")]
        public string RESPALDO_GABConnectionString {
            get {
                return ((string)(this["RESPALDO_GABConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:189.206.160.206,2352;Initial Catalog=GAB_Irapuato;Persist Securit" +
            "y Info=True;User ID=sa;Password=Gabira2026$;Encrypt=False")]
        public string GAB_IrapuatoConnectionString2 {
            get {
                return ((string)(this["GAB_IrapuatoConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:189.206.160.206,2352;Initial Catalog=GAB_Irapuato;Persist Securit" +
            "y Info=True;User ID=sa;Encrypt=False")]
        public string GAB_IrapuatoConnectionString3 {
            get {
                return ((string)(this["GAB_IrapuatoConnectionString3"]));
            }
        }
    }
}
