#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tickets")]
	public partial class dcTicketsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdministrador(Administrador instance);
    partial void UpdateAdministrador(Administrador instance);
    partial void DeleteAdministrador(Administrador instance);
    partial void InsertServicioEstado(ServicioEstado instance);
    partial void UpdateServicioEstado(ServicioEstado instance);
    partial void DeleteServicioEstado(ServicioEstado instance);
    partial void InsertTrabajador(Trabajador instance);
    partial void UpdateTrabajador(Trabajador instance);
    partial void DeleteTrabajador(Trabajador instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertDepartamento(Departamento instance);
    partial void UpdateDepartamento(Departamento instance);
    partial void DeleteDepartamento(Departamento instance);
    partial void InsertComentario(Comentario instance);
    partial void UpdateComentario(Comentario instance);
    partial void DeleteComentario(Comentario instance);
    partial void InsertPersona(Persona instance);
    partial void UpdatePersona(Persona instance);
    partial void DeletePersona(Persona instance);
    partial void InsertServicio(Servicio instance);
    partial void UpdateServicio(Servicio instance);
    partial void DeleteServicio(Servicio instance);
    #endregion
		
		public dcTicketsDataContext() : 
				base(global::Datos.Properties.Settings.Default.TicketsConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcTicketsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Administrador> Administrador
		{
			get
			{
				return this.GetTable<Administrador>();
			}
		}
		
		public System.Data.Linq.Table<ServicioEstado> ServicioEstado
		{
			get
			{
				return this.GetTable<ServicioEstado>();
			}
		}
		
		public System.Data.Linq.Table<Trabajador> Trabajador
		{
			get
			{
				return this.GetTable<Trabajador>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Departamento> Departamento
		{
			get
			{
				return this.GetTable<Departamento>();
			}
		}
		
		public System.Data.Linq.Table<Comentario> Comentario
		{
			get
			{
				return this.GetTable<Comentario>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Persona
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<Servicio> Servicio
		{
			get
			{
				return this.GetTable<Servicio>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosSolicitados")]
		public ISingleResult<sp_Get_ServiciosSolicitadosResult> sp_Get_ServiciosSolicitados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosSolicitadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosAsignados")]
		public ISingleResult<sp_Get_ServiciosAsignadosResult> sp_Get_ServiciosAsignados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosAsignadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Get_ServiciosFinalizados")]
		public ISingleResult<sp_Get_ServiciosFinalizadosResult> sp_Get_ServiciosFinalizados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_USER", DbType="Int")] System.Nullable<int> iD_USER, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DEP_ID", DbType="Int")] System.Nullable<int> dEP_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_USER, dEP_ID);
			return ((ISingleResult<sp_Get_ServiciosFinalizadosResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrador")]
	public partial class Administrador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _adm_ID;
		
		private int _per_ID;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadm_IDChanging(int value);
    partial void Onadm_IDChanged();
    partial void Onper_IDChanging(int value);
    partial void Onper_IDChanged();
    #endregion
		
		public Administrador()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int adm_ID
		{
			get
			{
				return this._adm_ID;
			}
			set
			{
				if ((this._adm_ID != value))
				{
					this.Onadm_IDChanging(value);
					this.SendPropertyChanging();
					this._adm_ID = value;
					this.SendPropertyChanged("adm_ID");
					this.Onadm_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID", DbType="Int NOT NULL")]
		public int per_ID
		{
			get
			{
				return this._per_ID;
			}
			set
			{
				if ((this._per_ID != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_IDChanging(value);
					this.SendPropertyChanging();
					this._per_ID = value;
					this.SendPropertyChanged("per_ID");
					this.Onper_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Administrador", Storage="_Persona", ThisKey="per_ID", OtherKey="per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Administrador.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Administrador.Add(this);
						this._per_ID = value.per_ID;
					}
					else
					{
						this._per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServicioEstado")]
	public partial class ServicioEstado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sere_ID;
		
		private string _sere_Clave;
		
		private string _sere_Descripcion;
		
		private EntitySet<Servicio> _Servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsere_IDChanging(int value);
    partial void Onsere_IDChanged();
    partial void Onsere_ClaveChanging(string value);
    partial void Onsere_ClaveChanged();
    partial void Onsere_DescripcionChanging(string value);
    partial void Onsere_DescripcionChanged();
    #endregion
		
		public ServicioEstado()
		{
			this._Servicio = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicio), new Action<Servicio>(this.detach_Servicio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sere_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int sere_ID
		{
			get
			{
				return this._sere_ID;
			}
			set
			{
				if ((this._sere_ID != value))
				{
					this.Onsere_IDChanging(value);
					this.SendPropertyChanging();
					this._sere_ID = value;
					this.SendPropertyChanged("sere_ID");
					this.Onsere_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sere_Clave", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string sere_Clave
		{
			get
			{
				return this._sere_Clave;
			}
			set
			{
				if ((this._sere_Clave != value))
				{
					this.Onsere_ClaveChanging(value);
					this.SendPropertyChanging();
					this._sere_Clave = value;
					this.SendPropertyChanged("sere_Clave");
					this.Onsere_ClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sere_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sere_Descripcion
		{
			get
			{
				return this._sere_Descripcion;
			}
			set
			{
				if ((this._sere_Descripcion != value))
				{
					this.Onsere_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._sere_Descripcion = value;
					this.SendPropertyChanged("sere_Descripcion");
					this.Onsere_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ServicioEstado_Servicio", Storage="_Servicio", ThisKey="sere_ID", OtherKey="sere_ID")]
		public EntitySet<Servicio> Servicio
		{
			get
			{
				return this._Servicio;
			}
			set
			{
				this._Servicio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Servicio(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.ServicioEstado = this;
		}
		
		private void detach_Servicio(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.ServicioEstado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Trabajador")]
	public partial class Trabajador : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tra_ID;
		
		private int _per_ID;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontra_IDChanging(int value);
    partial void Ontra_IDChanged();
    partial void Onper_IDChanging(int value);
    partial void Onper_IDChanged();
    #endregion
		
		public Trabajador()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tra_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tra_ID
		{
			get
			{
				return this._tra_ID;
			}
			set
			{
				if ((this._tra_ID != value))
				{
					this.Ontra_IDChanging(value);
					this.SendPropertyChanging();
					this._tra_ID = value;
					this.SendPropertyChanged("tra_ID");
					this.Ontra_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID", DbType="Int NOT NULL")]
		public int per_ID
		{
			get
			{
				return this._per_ID;
			}
			set
			{
				if ((this._per_ID != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_IDChanging(value);
					this.SendPropertyChanging();
					this._per_ID = value;
					this.SendPropertyChanged("per_ID");
					this.Onper_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Trabajador", Storage="_Persona", ThisKey="per_ID", OtherKey="per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Trabajador.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Trabajador.Add(this);
						this._per_ID = value.per_ID;
					}
					else
					{
						this._per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_ID;
		
		private string _usu_Usuario;
		
		private string _usu_Password;
		
		private int _per_ID;
		
		private EntityRef<Persona> _Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_IDChanging(int value);
    partial void Onusu_IDChanged();
    partial void Onusu_UsuarioChanging(string value);
    partial void Onusu_UsuarioChanged();
    partial void Onusu_PasswordChanging(string value);
    partial void Onusu_PasswordChanged();
    partial void Onper_IDChanging(int value);
    partial void Onper_IDChanged();
    #endregion
		
		public Usuario()
		{
			this._Persona = default(EntityRef<Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int usu_ID
		{
			get
			{
				return this._usu_ID;
			}
			set
			{
				if ((this._usu_ID != value))
				{
					this.Onusu_IDChanging(value);
					this.SendPropertyChanging();
					this._usu_ID = value;
					this.SendPropertyChanged("usu_ID");
					this.Onusu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_Usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_Usuario
		{
			get
			{
				return this._usu_Usuario;
			}
			set
			{
				if ((this._usu_Usuario != value))
				{
					this.Onusu_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._usu_Usuario = value;
					this.SendPropertyChanged("usu_Usuario");
					this.Onusu_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usu_Password
		{
			get
			{
				return this._usu_Password;
			}
			set
			{
				if ((this._usu_Password != value))
				{
					this.Onusu_PasswordChanging(value);
					this.SendPropertyChanging();
					this._usu_Password = value;
					this.SendPropertyChanged("usu_Password");
					this.Onusu_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID", DbType="Int NOT NULL")]
		public int per_ID
		{
			get
			{
				return this._per_ID;
			}
			set
			{
				if ((this._per_ID != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_IDChanging(value);
					this.SendPropertyChanging();
					this._per_ID = value;
					this.SendPropertyChanged("per_ID");
					this.Onper_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Persona", ThisKey="per_ID", OtherKey="per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Usuario.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Usuario.Add(this);
						this._per_ID = value.per_ID;
					}
					else
					{
						this._per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departamento")]
	public partial class Departamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dep_ID;
		
		private string _dep_Departamento;
		
		private bool _dep_AtiendeServicios;
		
		private EntitySet<Persona> _Persona;
		
		private EntitySet<Servicio> _Servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondep_IDChanging(int value);
    partial void Ondep_IDChanged();
    partial void Ondep_DepartamentoChanging(string value);
    partial void Ondep_DepartamentoChanged();
    partial void Ondep_AtiendeServiciosChanging(bool value);
    partial void Ondep_AtiendeServiciosChanged();
    #endregion
		
		public Departamento()
		{
			this._Persona = new EntitySet<Persona>(new Action<Persona>(this.attach_Persona), new Action<Persona>(this.detach_Persona));
			this._Servicio = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicio), new Action<Servicio>(this.detach_Servicio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int dep_ID
		{
			get
			{
				return this._dep_ID;
			}
			set
			{
				if ((this._dep_ID != value))
				{
					this.Ondep_IDChanging(value);
					this.SendPropertyChanging();
					this._dep_ID = value;
					this.SendPropertyChanged("dep_ID");
					this.Ondep_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_Departamento", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dep_Departamento
		{
			get
			{
				return this._dep_Departamento;
			}
			set
			{
				if ((this._dep_Departamento != value))
				{
					this.Ondep_DepartamentoChanging(value);
					this.SendPropertyChanging();
					this._dep_Departamento = value;
					this.SendPropertyChanged("dep_Departamento");
					this.Ondep_DepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_AtiendeServicios", DbType="Bit NOT NULL")]
		public bool dep_AtiendeServicios
		{
			get
			{
				return this._dep_AtiendeServicios;
			}
			set
			{
				if ((this._dep_AtiendeServicios != value))
				{
					this.Ondep_AtiendeServiciosChanging(value);
					this.SendPropertyChanging();
					this._dep_AtiendeServicios = value;
					this.SendPropertyChanged("dep_AtiendeServicios");
					this.Ondep_AtiendeServiciosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Persona", Storage="_Persona", ThisKey="dep_ID", OtherKey="dep_ID")]
		public EntitySet<Persona> Persona
		{
			get
			{
				return this._Persona;
			}
			set
			{
				this._Persona.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Servicio", Storage="_Servicio", ThisKey="dep_ID", OtherKey="ser_DeptoQueAtiende")]
		public EntitySet<Servicio> Servicio
		{
			get
			{
				return this._Servicio;
			}
			set
			{
				this._Servicio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Persona(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Persona(Persona entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
		
		private void attach_Servicio(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = this;
		}
		
		private void detach_Servicio(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Departamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Comentario")]
	public partial class Comentario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _com_ID;
		
		private int _ser_ID;
		
		private string _com_Comentario;
		
		private System.DateTime _com_FechaCom;
		
		private int _per_ID;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Servicio> _Servicio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncom_IDChanging(int value);
    partial void Oncom_IDChanged();
    partial void Onser_IDChanging(int value);
    partial void Onser_IDChanged();
    partial void Oncom_ComentarioChanging(string value);
    partial void Oncom_ComentarioChanged();
    partial void Oncom_FechaComChanging(System.DateTime value);
    partial void Oncom_FechaComChanged();
    partial void Onper_IDChanging(int value);
    partial void Onper_IDChanged();
    #endregion
		
		public Comentario()
		{
			this._Persona = default(EntityRef<Persona>);
			this._Servicio = default(EntityRef<Servicio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int com_ID
		{
			get
			{
				return this._com_ID;
			}
			set
			{
				if ((this._com_ID != value))
				{
					this.Oncom_IDChanging(value);
					this.SendPropertyChanging();
					this._com_ID = value;
					this.SendPropertyChanged("com_ID");
					this.Oncom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_ID", DbType="Int NOT NULL")]
		public int ser_ID
		{
			get
			{
				return this._ser_ID;
			}
			set
			{
				if ((this._ser_ID != value))
				{
					if (this._Servicio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onser_IDChanging(value);
					this.SendPropertyChanging();
					this._ser_ID = value;
					this.SendPropertyChanged("ser_ID");
					this.Onser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_Comentario", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string com_Comentario
		{
			get
			{
				return this._com_Comentario;
			}
			set
			{
				if ((this._com_Comentario != value))
				{
					this.Oncom_ComentarioChanging(value);
					this.SendPropertyChanging();
					this._com_Comentario = value;
					this.SendPropertyChanged("com_Comentario");
					this.Oncom_ComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_FechaCom", DbType="DateTime NOT NULL")]
		public System.DateTime com_FechaCom
		{
			get
			{
				return this._com_FechaCom;
			}
			set
			{
				if ((this._com_FechaCom != value))
				{
					this.Oncom_FechaComChanging(value);
					this.SendPropertyChanging();
					this._com_FechaCom = value;
					this.SendPropertyChanged("com_FechaCom");
					this.Oncom_FechaComChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID", DbType="Int NOT NULL")]
		public int per_ID
		{
			get
			{
				return this._per_ID;
			}
			set
			{
				if ((this._per_ID != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_IDChanging(value);
					this.SendPropertyChanging();
					this._per_ID = value;
					this.SendPropertyChanged("per_ID");
					this.Onper_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Comentario", Storage="_Persona", ThisKey="per_ID", OtherKey="per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Comentario.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Comentario.Add(this);
						this._per_ID = value.per_ID;
					}
					else
					{
						this._per_ID = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicio_Comentario", Storage="_Servicio", ThisKey="ser_ID", OtherKey="ser_ID", IsForeignKey=true)]
		public Servicio Servicio
		{
			get
			{
				return this._Servicio.Entity;
			}
			set
			{
				Servicio previousValue = this._Servicio.Entity;
				if (((previousValue != value) 
							|| (this._Servicio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Servicio.Entity = null;
						previousValue.Comentario.Remove(this);
					}
					this._Servicio.Entity = value;
					if ((value != null))
					{
						value.Comentario.Add(this);
						this._ser_ID = value.ser_ID;
					}
					else
					{
						this._ser_ID = default(int);
					}
					this.SendPropertyChanged("Servicio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _per_ID;
		
		private string _per_Nombre;
		
		private string _per_ApePat;
		
		private string _per_ApeMat;
		
		private string _per_Email;
		
		private string _per_ExtTelefono;
		
		private int _dep_ID;
		
		private bool _per_IsActivo;
		
		private EntitySet<Administrador> _Administrador;
		
		private EntitySet<Trabajador> _Trabajador;
		
		private EntitySet<Usuario> _Usuario;
		
		private EntitySet<Comentario> _Comentario;
		
		private EntitySet<Servicio> _Servicio;
		
		private EntitySet<Servicio> _Servicio1;
		
		private EntityRef<Departamento> _Departamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onper_IDChanging(int value);
    partial void Onper_IDChanged();
    partial void Onper_NombreChanging(string value);
    partial void Onper_NombreChanged();
    partial void Onper_ApePatChanging(string value);
    partial void Onper_ApePatChanged();
    partial void Onper_ApeMatChanging(string value);
    partial void Onper_ApeMatChanged();
    partial void Onper_EmailChanging(string value);
    partial void Onper_EmailChanged();
    partial void Onper_ExtTelefonoChanging(string value);
    partial void Onper_ExtTelefonoChanged();
    partial void Ondep_IDChanging(int value);
    partial void Ondep_IDChanged();
    partial void Onper_IsActivoChanging(bool value);
    partial void Onper_IsActivoChanged();
    #endregion
		
		public Persona()
		{
			this._Administrador = new EntitySet<Administrador>(new Action<Administrador>(this.attach_Administrador), new Action<Administrador>(this.detach_Administrador));
			this._Trabajador = new EntitySet<Trabajador>(new Action<Trabajador>(this.attach_Trabajador), new Action<Trabajador>(this.detach_Trabajador));
			this._Usuario = new EntitySet<Usuario>(new Action<Usuario>(this.attach_Usuario), new Action<Usuario>(this.detach_Usuario));
			this._Comentario = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentario), new Action<Comentario>(this.detach_Comentario));
			this._Servicio = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicio), new Action<Servicio>(this.detach_Servicio));
			this._Servicio1 = new EntitySet<Servicio>(new Action<Servicio>(this.attach_Servicio1), new Action<Servicio>(this.detach_Servicio1));
			this._Departamento = default(EntityRef<Departamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int per_ID
		{
			get
			{
				return this._per_ID;
			}
			set
			{
				if ((this._per_ID != value))
				{
					this.Onper_IDChanging(value);
					this.SendPropertyChanging();
					this._per_ID = value;
					this.SendPropertyChanged("per_ID");
					this.Onper_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_Nombre", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string per_Nombre
		{
			get
			{
				return this._per_Nombre;
			}
			set
			{
				if ((this._per_Nombre != value))
				{
					this.Onper_NombreChanging(value);
					this.SendPropertyChanging();
					this._per_Nombre = value;
					this.SendPropertyChanged("per_Nombre");
					this.Onper_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ApePat", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string per_ApePat
		{
			get
			{
				return this._per_ApePat;
			}
			set
			{
				if ((this._per_ApePat != value))
				{
					this.Onper_ApePatChanging(value);
					this.SendPropertyChanging();
					this._per_ApePat = value;
					this.SendPropertyChanged("per_ApePat");
					this.Onper_ApePatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ApeMat", DbType="VarChar(200)")]
		public string per_ApeMat
		{
			get
			{
				return this._per_ApeMat;
			}
			set
			{
				if ((this._per_ApeMat != value))
				{
					this.Onper_ApeMatChanging(value);
					this.SendPropertyChanging();
					this._per_ApeMat = value;
					this.SendPropertyChanged("per_ApeMat");
					this.Onper_ApeMatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_Email
		{
			get
			{
				return this._per_Email;
			}
			set
			{
				if ((this._per_Email != value))
				{
					this.Onper_EmailChanging(value);
					this.SendPropertyChanging();
					this._per_Email = value;
					this.SendPropertyChanged("per_Email");
					this.Onper_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ExtTelefono", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_ExtTelefono
		{
			get
			{
				return this._per_ExtTelefono;
			}
			set
			{
				if ((this._per_ExtTelefono != value))
				{
					this.Onper_ExtTelefonoChanging(value);
					this.SendPropertyChanging();
					this._per_ExtTelefono = value;
					this.SendPropertyChanged("per_ExtTelefono");
					this.Onper_ExtTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_ID", DbType="Int NOT NULL")]
		public int dep_ID
		{
			get
			{
				return this._dep_ID;
			}
			set
			{
				if ((this._dep_ID != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondep_IDChanging(value);
					this.SendPropertyChanging();
					this._dep_ID = value;
					this.SendPropertyChanged("dep_ID");
					this.Ondep_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_IsActivo", DbType="Bit NOT NULL")]
		public bool per_IsActivo
		{
			get
			{
				return this._per_IsActivo;
			}
			set
			{
				if ((this._per_IsActivo != value))
				{
					this.Onper_IsActivoChanging(value);
					this.SendPropertyChanging();
					this._per_IsActivo = value;
					this.SendPropertyChanged("per_IsActivo");
					this.Onper_IsActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Administrador", Storage="_Administrador", ThisKey="per_ID", OtherKey="per_ID")]
		public EntitySet<Administrador> Administrador
		{
			get
			{
				return this._Administrador;
			}
			set
			{
				this._Administrador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Trabajador", Storage="_Trabajador", ThisKey="per_ID", OtherKey="per_ID")]
		public EntitySet<Trabajador> Trabajador
		{
			get
			{
				return this._Trabajador;
			}
			set
			{
				this._Trabajador.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Usuario", Storage="_Usuario", ThisKey="per_ID", OtherKey="per_ID")]
		public EntitySet<Usuario> Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				this._Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Comentario", Storage="_Comentario", ThisKey="per_ID", OtherKey="per_ID")]
		public EntitySet<Comentario> Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				this._Comentario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio", Storage="_Servicio", ThisKey="per_ID", OtherKey="per_ID_Levanto")]
		public EntitySet<Servicio> Servicio
		{
			get
			{
				return this._Servicio;
			}
			set
			{
				this._Servicio.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio1", Storage="_Servicio1", ThisKey="per_ID", OtherKey="per_ID_Atiende")]
		public EntitySet<Servicio> Servicio1
		{
			get
			{
				return this._Servicio1;
			}
			set
			{
				this._Servicio1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Persona", Storage="_Departamento", ThisKey="dep_ID", OtherKey="dep_ID", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Persona.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Persona.Add(this);
						this._dep_ID = value.dep_ID;
					}
					else
					{
						this._dep_ID = default(int);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Administrador(Administrador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Administrador(Administrador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Trabajador(Trabajador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Trabajador(Trabajador entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Usuario(Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Servicio(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Persona = this;
		}
		
		private void detach_Servicio(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Persona = null;
		}
		
		private void attach_Servicio1(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Persona1 = this;
		}
		
		private void detach_Servicio1(Servicio entity)
		{
			this.SendPropertyChanging();
			entity.Persona1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servicio")]
	public partial class Servicio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ser_ID;
		
		private int _sere_ID;
		
		private int _per_ID_Levanto;
		
		private System.Nullable<int> _per_ID_Atiende;
		
		private string _ser_Incidente;
		
		private System.DateTime _ser_FechaIngreso;
		
		private System.DateTime _ser_FechaUltimoE;
		
		private System.Nullable<int> _ser_DeptoQueAtiende;
		
		private string _ser_Area;
		
		private string _ser_Equipo;
		
		private string _ser_Nombre_Atiende;
		
		private System.Nullable<int> _ser_Num_Fotos;
		
		private System.Nullable<System.DateTime> _ser_FechaEstimadaFin;
		
		private EntitySet<Comentario> _Comentario;
		
		private EntityRef<Departamento> _Departamento;
		
		private EntityRef<Persona> _Persona;
		
		private EntityRef<Persona> _Persona1;
		
		private EntityRef<ServicioEstado> _ServicioEstado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onser_IDChanging(int value);
    partial void Onser_IDChanged();
    partial void Onsere_IDChanging(int value);
    partial void Onsere_IDChanged();
    partial void Onper_ID_LevantoChanging(int value);
    partial void Onper_ID_LevantoChanged();
    partial void Onper_ID_AtiendeChanging(System.Nullable<int> value);
    partial void Onper_ID_AtiendeChanged();
    partial void Onser_IncidenteChanging(string value);
    partial void Onser_IncidenteChanged();
    partial void Onser_FechaIngresoChanging(System.DateTime value);
    partial void Onser_FechaIngresoChanged();
    partial void Onser_FechaUltimoEChanging(System.DateTime value);
    partial void Onser_FechaUltimoEChanged();
    partial void Onser_DeptoQueAtiendeChanging(System.Nullable<int> value);
    partial void Onser_DeptoQueAtiendeChanged();
    partial void Onser_AreaChanging(string value);
    partial void Onser_AreaChanged();
    partial void Onser_EquipoChanging(string value);
    partial void Onser_EquipoChanged();
    partial void Onser_Nombre_AtiendeChanging(string value);
    partial void Onser_Nombre_AtiendeChanged();
    partial void Onser_Num_FotosChanging(System.Nullable<int> value);
    partial void Onser_Num_FotosChanged();
    partial void Onser_FechaEstimadaFinChanging(System.Nullable<System.DateTime> value);
    partial void Onser_FechaEstimadaFinChanged();
    #endregion
		
		public Servicio()
		{
			this._Comentario = new EntitySet<Comentario>(new Action<Comentario>(this.attach_Comentario), new Action<Comentario>(this.detach_Comentario));
			this._Departamento = default(EntityRef<Departamento>);
			this._Persona = default(EntityRef<Persona>);
			this._Persona1 = default(EntityRef<Persona>);
			this._ServicioEstado = default(EntityRef<ServicioEstado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ser_ID
		{
			get
			{
				return this._ser_ID;
			}
			set
			{
				if ((this._ser_ID != value))
				{
					this.Onser_IDChanging(value);
					this.SendPropertyChanging();
					this._ser_ID = value;
					this.SendPropertyChanged("ser_ID");
					this.Onser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sere_ID", DbType="Int NOT NULL")]
		public int sere_ID
		{
			get
			{
				return this._sere_ID;
			}
			set
			{
				if ((this._sere_ID != value))
				{
					if (this._ServicioEstado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsere_IDChanging(value);
					this.SendPropertyChanging();
					this._sere_ID = value;
					this.SendPropertyChanged("sere_ID");
					this.Onsere_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID_Levanto", DbType="Int NOT NULL")]
		public int per_ID_Levanto
		{
			get
			{
				return this._per_ID_Levanto;
			}
			set
			{
				if ((this._per_ID_Levanto != value))
				{
					if (this._Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_ID_LevantoChanging(value);
					this.SendPropertyChanging();
					this._per_ID_Levanto = value;
					this.SendPropertyChanged("per_ID_Levanto");
					this.Onper_ID_LevantoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ID_Atiende", DbType="Int")]
		public System.Nullable<int> per_ID_Atiende
		{
			get
			{
				return this._per_ID_Atiende;
			}
			set
			{
				if ((this._per_ID_Atiende != value))
				{
					if (this._Persona1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_ID_AtiendeChanging(value);
					this.SendPropertyChanging();
					this._per_ID_Atiende = value;
					this.SendPropertyChanged("per_ID_Atiende");
					this.Onper_ID_AtiendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_Incidente", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string ser_Incidente
		{
			get
			{
				return this._ser_Incidente;
			}
			set
			{
				if ((this._ser_Incidente != value))
				{
					this.Onser_IncidenteChanging(value);
					this.SendPropertyChanging();
					this._ser_Incidente = value;
					this.SendPropertyChanged("ser_Incidente");
					this.Onser_IncidenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_FechaIngreso", DbType="DateTime NOT NULL")]
		public System.DateTime ser_FechaIngreso
		{
			get
			{
				return this._ser_FechaIngreso;
			}
			set
			{
				if ((this._ser_FechaIngreso != value))
				{
					this.Onser_FechaIngresoChanging(value);
					this.SendPropertyChanging();
					this._ser_FechaIngreso = value;
					this.SendPropertyChanged("ser_FechaIngreso");
					this.Onser_FechaIngresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_FechaUltimoE", DbType="DateTime NOT NULL")]
		public System.DateTime ser_FechaUltimoE
		{
			get
			{
				return this._ser_FechaUltimoE;
			}
			set
			{
				if ((this._ser_FechaUltimoE != value))
				{
					this.Onser_FechaUltimoEChanging(value);
					this.SendPropertyChanging();
					this._ser_FechaUltimoE = value;
					this.SendPropertyChanged("ser_FechaUltimoE");
					this.Onser_FechaUltimoEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_DeptoQueAtiende", DbType="Int")]
		public System.Nullable<int> ser_DeptoQueAtiende
		{
			get
			{
				return this._ser_DeptoQueAtiende;
			}
			set
			{
				if ((this._ser_DeptoQueAtiende != value))
				{
					if (this._Departamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onser_DeptoQueAtiendeChanging(value);
					this.SendPropertyChanging();
					this._ser_DeptoQueAtiende = value;
					this.SendPropertyChanged("ser_DeptoQueAtiende");
					this.Onser_DeptoQueAtiendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_Area", DbType="VarChar(50)")]
		public string ser_Area
		{
			get
			{
				return this._ser_Area;
			}
			set
			{
				if ((this._ser_Area != value))
				{
					this.Onser_AreaChanging(value);
					this.SendPropertyChanging();
					this._ser_Area = value;
					this.SendPropertyChanged("ser_Area");
					this.Onser_AreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_Equipo", DbType="VarChar(50)")]
		public string ser_Equipo
		{
			get
			{
				return this._ser_Equipo;
			}
			set
			{
				if ((this._ser_Equipo != value))
				{
					this.Onser_EquipoChanging(value);
					this.SendPropertyChanging();
					this._ser_Equipo = value;
					this.SendPropertyChanged("ser_Equipo");
					this.Onser_EquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_Nombre_Atiende", DbType="VarChar(50)")]
		public string ser_Nombre_Atiende
		{
			get
			{
				return this._ser_Nombre_Atiende;
			}
			set
			{
				if ((this._ser_Nombre_Atiende != value))
				{
					this.Onser_Nombre_AtiendeChanging(value);
					this.SendPropertyChanging();
					this._ser_Nombre_Atiende = value;
					this.SendPropertyChanged("ser_Nombre_Atiende");
					this.Onser_Nombre_AtiendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_Num_Fotos", DbType="Int")]
		public System.Nullable<int> ser_Num_Fotos
		{
			get
			{
				return this._ser_Num_Fotos;
			}
			set
			{
				if ((this._ser_Num_Fotos != value))
				{
					this.Onser_Num_FotosChanging(value);
					this.SendPropertyChanging();
					this._ser_Num_Fotos = value;
					this.SendPropertyChanged("ser_Num_Fotos");
					this.Onser_Num_FotosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ser_FechaEstimadaFin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ser_FechaEstimadaFin
		{
			get
			{
				return this._ser_FechaEstimadaFin;
			}
			set
			{
				if ((this._ser_FechaEstimadaFin != value))
				{
					this.Onser_FechaEstimadaFinChanging(value);
					this.SendPropertyChanging();
					this._ser_FechaEstimadaFin = value;
					this.SendPropertyChanged("ser_FechaEstimadaFin");
					this.Onser_FechaEstimadaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Servicio_Comentario", Storage="_Comentario", ThisKey="ser_ID", OtherKey="ser_ID")]
		public EntitySet<Comentario> Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				this._Comentario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Departamento_Servicio", Storage="_Departamento", ThisKey="ser_DeptoQueAtiende", OtherKey="dep_ID", IsForeignKey=true)]
		public Departamento Departamento
		{
			get
			{
				return this._Departamento.Entity;
			}
			set
			{
				Departamento previousValue = this._Departamento.Entity;
				if (((previousValue != value) 
							|| (this._Departamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Departamento.Entity = null;
						previousValue.Servicio.Remove(this);
					}
					this._Departamento.Entity = value;
					if ((value != null))
					{
						value.Servicio.Add(this);
						this._ser_DeptoQueAtiende = value.dep_ID;
					}
					else
					{
						this._ser_DeptoQueAtiende = default(Nullable<int>);
					}
					this.SendPropertyChanged("Departamento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio", Storage="_Persona", ThisKey="per_ID_Levanto", OtherKey="per_ID", IsForeignKey=true)]
		public Persona Persona
		{
			get
			{
				return this._Persona.Entity;
			}
			set
			{
				Persona previousValue = this._Persona.Entity;
				if (((previousValue != value) 
							|| (this._Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona.Entity = null;
						previousValue.Servicio.Remove(this);
					}
					this._Persona.Entity = value;
					if ((value != null))
					{
						value.Servicio.Add(this);
						this._per_ID_Levanto = value.per_ID;
					}
					else
					{
						this._per_ID_Levanto = default(int);
					}
					this.SendPropertyChanged("Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Persona_Servicio1", Storage="_Persona1", ThisKey="per_ID_Atiende", OtherKey="per_ID", IsForeignKey=true)]
		public Persona Persona1
		{
			get
			{
				return this._Persona1.Entity;
			}
			set
			{
				Persona previousValue = this._Persona1.Entity;
				if (((previousValue != value) 
							|| (this._Persona1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Persona1.Entity = null;
						previousValue.Servicio1.Remove(this);
					}
					this._Persona1.Entity = value;
					if ((value != null))
					{
						value.Servicio1.Add(this);
						this._per_ID_Atiende = value.per_ID;
					}
					else
					{
						this._per_ID_Atiende = default(Nullable<int>);
					}
					this.SendPropertyChanged("Persona1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ServicioEstado_Servicio", Storage="_ServicioEstado", ThisKey="sere_ID", OtherKey="sere_ID", IsForeignKey=true)]
		public ServicioEstado ServicioEstado
		{
			get
			{
				return this._ServicioEstado.Entity;
			}
			set
			{
				ServicioEstado previousValue = this._ServicioEstado.Entity;
				if (((previousValue != value) 
							|| (this._ServicioEstado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ServicioEstado.Entity = null;
						previousValue.Servicio.Remove(this);
					}
					this._ServicioEstado.Entity = value;
					if ((value != null))
					{
						value.Servicio.Add(this);
						this._sere_ID = value.sere_ID;
					}
					else
					{
						this._sere_ID = default(int);
					}
					this.SendPropertyChanged("ServicioEstado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = this;
		}
		
		private void detach_Comentario(Comentario entity)
		{
			this.SendPropertyChanging();
			entity.Servicio = null;
		}
	}
	
	public partial class sp_Get_ServiciosSolicitadosResult
	{
		
		private int _ID;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private string _Nombre;
		
		private string _Asignado_A;
		
		private string _Area;
		
		private string _Equipo;
		
		private string _Incidente;
		
		private string _Estado;
		
		public sp_Get_ServiciosSolicitadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Asignado A]", Storage="_Asignado_A", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Asignado_A
		{
			get
			{
				return this._Asignado_A;
			}
			set
			{
				if ((this._Asignado_A != value))
				{
					this._Asignado_A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo", DbType="VarChar(50)")]
		public string Equipo
		{
			get
			{
				return this._Equipo;
			}
			set
			{
				if ((this._Equipo != value))
				{
					this._Equipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosAsignadosResult
	{
		
		private int _ID;
		
		private string _Nombre;
		
		private string _Area;
		
		private string _Equipo;
		
		private string _Incidente;
		
		private string _Comentarios;
		
		private string _Asignado_A;
		
		private string _Responsable;
		
		private System.DateTime _Fecha_Ingreso;
		
		private System.Nullable<System.DateTime> _Fecha_Estimada_Fin;
		
		private System.DateTime _Ultimo_Estado;
		
		public sp_Get_ServiciosAsignadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="VarChar(50)")]
		public string Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Equipo", DbType="VarChar(50)")]
		public string Equipo
		{
			get
			{
				return this._Equipo;
			}
			set
			{
				if ((this._Equipo != value))
				{
					this._Equipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				if ((this._Comentarios != value))
				{
					this._Comentarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Asignado A]", Storage="_Asignado_A", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Asignado_A
		{
			get
			{
				return this._Asignado_A;
			}
			set
			{
				if ((this._Asignado_A != value))
				{
					this._Asignado_A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsable", DbType="VarChar(50)")]
		public string Responsable
		{
			get
			{
				return this._Responsable;
			}
			set
			{
				if ((this._Responsable != value))
				{
					this._Responsable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_Ingreso
		{
			get
			{
				return this._Fecha_Ingreso;
			}
			set
			{
				if ((this._Fecha_Ingreso != value))
				{
					this._Fecha_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Estimada_Fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Estimada_Fin
		{
			get
			{
				return this._Fecha_Estimada_Fin;
			}
			set
			{
				if ((this._Fecha_Estimada_Fin != value))
				{
					this._Fecha_Estimada_Fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultimo_Estado", DbType="DateTime NOT NULL")]
		public System.DateTime Ultimo_Estado
		{
			get
			{
				return this._Ultimo_Estado;
			}
			set
			{
				if ((this._Ultimo_Estado != value))
				{
					this._Ultimo_Estado = value;
				}
			}
		}
	}
	
	public partial class sp_Get_ServiciosFinalizadosResult
	{
		
		private int _ID;
		
		private int _Usuario;
		
		private string _Nombre;
		
		private string _Incidente;
		
		private string _Comentarios;
		
		private string _Asignado_A;
		
		private string _Estado;
		
		private System.DateTime _Fecha_de_Ingreso;
		
		private System.Nullable<System.DateTime> _Fecha_Estimada_Fin;
		
		private System.DateTime _Fecha_de_último_Estado;
		
		private string _Duración;
		
		public sp_Get_ServiciosFinalizadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="Int NOT NULL")]
		public int Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(602) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Incidente", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Incidente
		{
			get
			{
				return this._Incidente;
			}
			set
			{
				if ((this._Incidente != value))
				{
					this._Incidente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentarios", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Comentarios
		{
			get
			{
				return this._Comentarios;
			}
			set
			{
				if ((this._Comentarios != value))
				{
					this._Comentarios = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Asignado A]", Storage="_Asignado_A", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Asignado_A
		{
			get
			{
				return this._Asignado_A;
			}
			set
			{
				if ((this._Asignado_A != value))
				{
					this._Asignado_A = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de Ingreso]", Storage="_Fecha_de_Ingreso", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_Ingreso
		{
			get
			{
				return this._Fecha_de_Ingreso;
			}
			set
			{
				if ((this._Fecha_de_Ingreso != value))
				{
					this._Fecha_de_Ingreso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Estimada_Fin", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Estimada_Fin
		{
			get
			{
				return this._Fecha_Estimada_Fin;
			}
			set
			{
				if ((this._Fecha_Estimada_Fin != value))
				{
					this._Fecha_Estimada_Fin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha de último Estado]", Storage="_Fecha_de_último_Estado", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_de_último_Estado
		{
			get
			{
				return this._Fecha_de_último_Estado;
			}
			set
			{
				if ((this._Fecha_de_último_Estado != value))
				{
					this._Fecha_de_último_Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duración", DbType="VarChar(36)")]
		public string Duración
		{
			get
			{
				return this._Duración;
			}
			set
			{
				if ((this._Duración != value))
				{
					this._Duración = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
